import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiPlay, FiX, FiChevronLeft, FiChevronRight } from 'react-icons/fi';

const ThumbnailImage = ({ video, isLarge }) => {
  const autoGeneratedThumbnail = `https://img.youtube.com/vi/${video.id}/hqdefault.jpg`;
  
  // It's a custom thumbnail if the user provided one that differs from the default script-generated one
  const isCustom = video.thumbnail && video.thumbnail !== autoGeneratedThumbnail;
  const fallbackImg = isCustom ? video.thumbnail : autoGeneratedThumbnail;
  
  const initialImg = isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg));
  
  const [imgSrc, setImgSrc] = useState(initialImg);

  React.useEffect(() => {
    setImgSrc(isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg)));
  }, [video.id, video.customBg, video.thumbnail, isLarge, isCustom, fallbackImg]);

  return (
    <img 
      src={imgSrc} 
      alt={video.title}
      className={isLarge ? "absolute inset-0 w-full h-full object-cover opacity-80" : "w-full h-full object-cover"}
      onError={() => {
        if (imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
      onLoad={(e) => {
        // Detect YouTube's 120px gray placeholder for maxresdefault
        if (e.target.naturalWidth <= 120 && imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
    />
  );
};

const VideoPlaylist = ({ videos, category }) => {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isHoveringButton, setIsHoveringButton] = useState(false);
  const carouselRef = useRef(null);

  const scrollCarousel = (direction) => {
    if (carouselRef.current) {
      const scrollAmount = 350; 
      if (direction === 'up' || direction === 'down') {
        carouselRef.current.scrollBy({ top: direction === 'up' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
      } else {
        carouselRef.current.scrollBy({ left: direction === 'left' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
      }
    }
  };

  if (!videos || videos.length === 0) return null;

  const activeVideo = videos[activeIndex];

  return (
    <div className="w-full bg-white h-screen py-4 md:py-8 flex justify-center items-center border-b border-gray-200 font-main">
      <div className="w-full h-full max-h-[1000px] max-w-[1600px] px-4 md:px-8">
        
        {/* Netflix-style Main Poster */}
        <div className="relative w-full h-full bg-black rounded-2xl md:rounded-[2rem] overflow-hidden shadow-[0_20px_50px_rgba(0,0,0,0.5)] group/poster">
          
          {/* Background Media */}
          <AnimatePresence>
            {!isPlaying && (
              <motion.div 
                key={activeVideo.id}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.8 }}
                className="absolute inset-0"
              >
                <ThumbnailImage video={activeVideo} isLarge={true} />
                {/* Netflix style Vignette & Gradients */}
                <div className="absolute inset-0 bg-gradient-to-t from-[#08080C] via-[#08080C]/40 to-transparent"></div>
                <div className="absolute inset-0 bg-gradient-to-r from-[#08080C]/80 via-transparent to-transparent"></div>
                <div className="absolute inset-0 bg-gradient-to-r from-white/50 to-transparent mix-blend-overlay"></div>
                <div className="absolute inset-0 shadow-[inset_0_0_100px_rgba(0,0,0,0.8)]"></div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Video Player */}
          {isPlaying && (
            <div className="absolute inset-0 z-50 bg-black">
              <button
                onClick={() => setIsPlaying(false)}
                className="absolute top-6 right-6 z-50 bg-white/20 backdrop-blur-md text-white p-3 rounded-full hover:bg-white hover:text-black transition-all shadow-xl"
              >
                <FiX className="text-2xl" />
              </button>
              <iframe
                src={`https://www.youtube.com/embed/${activeVideo.id}?autoplay=1&rel=0`}
                title={activeVideo.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full border-0"
              />
            </div>
          )}

          {/* Content Overlays */}
          {!isPlaying && (
            <div className="absolute inset-0 flex flex-row justify-between z-20 pointer-events-none">
                
              {/* Full-width Dark Gradient at Bottom */}
              <div className="absolute bottom-0 left-0 right-0 h-[40%] md:h-1/2 bg-gradient-to-t from-black/90 via-black/50 to-transparent pointer-events-none z-0"></div>

              {/* Left-Aligned Hero Content */}
              <div className="flex-1 flex flex-col justify-end px-6 md:px-12 pt-10 md:pt-16 pb-8 md:pb-12 pointer-events-auto relative z-10">

                {/* Bottom Left Content */}
                <div className="flex flex-col items-start gap-2 md:gap-4 mt-auto relative z-10">
                  
                  {/* Video Title */}
                  <motion.h1 
                    key={`title-${activeVideo.id}`}
                    initial={{ x: -20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: 0.2, duration: 0.6 }}
                    className="text-base md:text-lg lg:text-xl font-main font-bold text-white tracking-wide drop-shadow-[0_4px_8px_rgba(0,0,0,0.9)] leading-tight text-left max-w-2xl"
                  >
                    {activeVideo.title}
                  </motion.h1>

                  {/* Category Title */}
                  <h3 className="text-3xl md:text-5xl lg:text-6xl xl:text-8xl font-hero font-extrabold text-brand-blue tracking-widest uppercase drop-shadow-[0_0_25px_currentColor]">
                    {category}
                  </h3>
                </div>

              </div>

              {/* Right Side Vertical Carousel */}
              <div className="w-72 md:w-96 lg:w-[420px] xl:w-[480px] h-full pointer-events-auto relative group/carousel flex flex-col items-center justify-center py-4 pr-4 md:pr-8 pl-4">
                <style>{`
                  .hide-scrollbar::-webkit-scrollbar {
                    display: none;
                  }
                `}</style>
                {/* Centered Scroll Arrows */}
                <div className="absolute inset-y-0 right-4 md:right-8 w-28 md:w-40 lg:w-48 xl:w-56 pointer-events-none flex flex-col justify-between items-center py-4 z-40">
                  <button 
                    onClick={() => scrollCarousel('up')}
                    className="pointer-events-auto bg-black/80 hover:bg-white hover:text-black text-white p-2 md:p-3 rounded-full opacity-0 group-hover/carousel:opacity-100 transition-all duration-300 shadow-xl border border-white/20"
                  >
                    <FiChevronLeft className="rotate-90" size={24} />
                  </button>
                  
                  <button 
                    onClick={() => scrollCarousel('down')}
                    className="pointer-events-auto bg-black/80 hover:bg-white hover:text-black text-white p-2 md:p-3 rounded-full opacity-0 group-hover/carousel:opacity-100 transition-all duration-300 shadow-xl border border-white/20"
                  >
                    <FiChevronRight className="rotate-90" size={24} />
                  </button>
                </div>

                <div 
                  ref={carouselRef}
                  data-lenis-prevent="true"
                  className={`flex flex-col gap-3 md:gap-4 px-4 py-8 h-full snap-y snap-mandatory hide-scrollbar relative w-full items-end pointer-events-none overscroll-contain ${isHoveringButton ? 'overflow-y-hidden' : 'overflow-y-auto'}`} 
                  style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
                >
                  {videos.map((video, index) => {
                      const isActive = index === activeIndex;
                      const episodeNumber = String(index + 1).padStart(2, '0');
                      
                      return (
                        <div key={video.id + index} className="flex items-center justify-end w-full snap-start group gap-3 md:gap-4">
                          
                          <AnimatePresence>
                            {isActive && (
                              <motion.div
                                initial={{ opacity: 0, x: 20, scale: 0.8 }}
                                animate={{ opacity: 1, x: 0, scale: 1 }}
                                exit={{ opacity: 0, x: 20, scale: 0.8 }}
                                transition={{ type: "spring", stiffness: 300, damping: 20 }}
                                className="z-50 whitespace-nowrap flex-shrink-0 pointer-events-auto"
                              >
                                <button
                                  onMouseEnter={() => setIsHoveringButton(true)}
                                  onMouseLeave={() => setIsHoveringButton(false)}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    setIsPlaying(true);
                                  }}
                                  className="flex items-center gap-2 bg-white text-black px-3 py-1.5 md:px-5 md:py-2.5 rounded-full font-bold text-sm md:text-base hover:bg-brand-blue hover:text-white hover:scale-105 transition-all shadow-[0_10px_30px_rgba(0,0,0,0.5)] group/playbtn"
                                >
                                  <FiPlay className="text-lg md:text-xl fill-current" /> Watch Now
                                </button>
                              </motion.div>
                            )}
                          </AnimatePresence>

                          <button
                            onClick={() => {
                              setActiveIndex(index);
                              setIsPlaying(false);
                            }}
                            className={`relative flex-shrink-0 w-28 md:w-40 lg:w-48 xl:w-56 aspect-video rounded-md overflow-hidden transition-all duration-500 cursor-pointer border-2 pointer-events-auto ${
                              isActive ? 'border-white scale-100 opacity-100 z-10' : 'border-transparent scale-95 opacity-50 hover:scale-100 hover:opacity-100'
                            }`}
                          >
                            <ThumbnailImage video={video} isLarge={false} />
                          {/* Darken unselected */}
                          {!isActive && (
                            <div className="absolute inset-0 bg-black/40"></div>
                          )}
                          
                          {/* Number Overlay */}
                          <div className="absolute bottom-2 left-3">
                            <span className="text-white/90 font-bold text-lg md:text-xl font-hero drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
                              {episodeNumber}
                            </span>
                          </div>
                          </button>
                        </div>
                      );
                  })}
                </div>
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default VideoPlaylist;
