import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiPlay, FiX, FiChevronLeft, FiChevronRight, FiChevronDown, FiTv, FiMic, FiBriefcase, FiMonitor, FiBookOpen, FiCpu, FiFilm, FiVideo } from 'react-icons/fi';
import { FaLightbulb } from 'react-icons/fa';
import YouTube from 'react-youtube';

const getCategoryIcon = (category, theme = 'blue') => {
  const iconColorClass = theme === 'red' ? 'text-brand-red' : 'text-[#1672EF]';
  const iconClass = `w-10 h-10 md:w-12 md:h-12 ${iconColorClass}`;
  switch (category?.toUpperCase()) {
    case "AD FILMS": return <FiTv className={iconClass} />;
    case "PODCASTS": return <FiMic className={iconClass} />;
    case "BRAND FILMS": return <FiBriefcase className={iconClass} />;
    case "ANIMATED EXPLAINERS": return <FiMonitor className={iconClass} />;
    case "L&D TRAINING FILMS": return <FiBookOpen className={iconClass} />;
    case "AI VIDEOS": return <FiCpu className={iconClass} />;
    case "SHORT FILMS": return <FiFilm className={iconClass} />;
    case "ANY CREATIVE FILMS": return <FaLightbulb className={iconClass} />;
    case "MICRODRAMA SHOWS": return <FiTv className={iconClass} />;
    case "FEATURE FILMS": return <FiFilm className={iconClass} />;
    case "WEB/TV SERIES": return <FiTv className={iconClass} />;
    case "MUSIC VIDEOS": return <FiMic className={iconClass} />;
    case "DOCUMENTARY FILMS": return <FiBookOpen className={iconClass} />;
    default: return <FiVideo className={iconClass} />;
  }
};

const getCategorySubtitle = (category) => {
  switch (category?.toUpperCase()) {
    case "AD FILMS": return "Captivating commercials that tell your brand's story and drive action.";
    case "PODCASTS": return "Inspiring conversations, expert insights, and real stories that drive impact.";
    case "BRAND FILMS": return "Cinematic narratives that establish your identity and build lasting trust.";
    case "ANIMATED EXPLAINERS": return "Simplifying complex ideas into engaging, easy-to-understand visual stories.";
    case "L&D TRAINING FILMS": return "Effective, engaging educational content to upskill and empower your team.";
    case "AI VIDEOS": return "Cutting-edge, AI-driven video content for the next generation of digital media.";
    case "SHORT FILMS": return "Creative, compelling narratives that evoke emotion and leave a lasting impression.";
    case "ANY CREATIVE FILMS": return "Unique, out-of-the-box video concepts tailored perfectly to your creative vision.";
    default: return "Inspiring video content that connects, engages, and converts.";
  }
};

const ThumbnailImage = ({ video, isLarge }) => {
  const autoGeneratedThumbnail = `https://img.youtube.com/vi/${video.id}/hqdefault.jpg`;
  
  // It's a custom thumbnail if the user provided one that differs from the default script-generated one
  const isCustom = video.thumbnail && video.thumbnail !== autoGeneratedThumbnail;
  const fallbackImg = isCustom ? video.thumbnail : autoGeneratedThumbnail;
  
  const initialImg = isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg));
  
  const [imgSrc, setImgSrc] = useState(initialImg);

  React.useEffect(() => {
    setImgSrc(isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg)));
  }, [video.id, video.customBg, video.thumbnail, isLarge, isCustom, fallbackImg]);

  return (
    <img 
      src={imgSrc} 
      alt={video.title}
      className={isLarge ? "absolute inset-0 w-full h-full object-cover" : "w-full h-full object-cover"}
      onError={() => {
        if (imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
      onLoad={(e) => {
        // Detect YouTube's 120px gray placeholder for maxresdefault
        if (e.target.naturalWidth <= 120 && imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
    />
  );
};

const VideoPlaylist = ({ videos, category, theme = 'blue' }) => {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isVideoPaused, setIsVideoPaused] = useState(false);
  const [ytPlayer, setYtPlayer] = useState(null);
  const [isHoveringButton, setIsHoveringButton] = useState(false);
  const [isMobilePlaylistOpen, setIsMobilePlaylistOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [isMobileLandscape, setIsMobileLandscape] = useState(false);
  const carouselRef = useRef(null);

  useEffect(() => {
    const checkMobile = () => {
      const isMobileWidth = window.innerWidth < 1024;
      const isLandscape = window.innerWidth > window.innerHeight && window.innerHeight < 600;
      setIsMobile(isMobileWidth && !isLandscape);
      setIsMobileLandscape(isMobileWidth && isLandscape);
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  useEffect(() => {
    setIsPlaying(false);
    setIsVideoPaused(false);
  }, [activeIndex]);

  useEffect(() => {
    const handleStopOtherVideos = (e) => {
      if (e.detail && e.detail.category !== category) {
        setIsPlaying(false);
        setIsVideoPaused(true);
        if (ytPlayer && typeof ytPlayer.pauseVideo === 'function') {
          ytPlayer.pauseVideo();
        }
      }
    };
    window.addEventListener('stopOtherVideos', handleStopOtherVideos);
    return () => window.removeEventListener('stopOtherVideos', handleStopOtherVideos);
  }, [category, ytPlayer]);

  const handlePlayVideo = (e) => {
    if (e && e.stopPropagation) e.stopPropagation();
    setIsPlaying(true);
    setIsVideoPaused(false);
    if (ytPlayer) ytPlayer.playVideo();
    window.dispatchEvent(new CustomEvent('videoPlaybackStarted'));
    window.dispatchEvent(new CustomEvent('stopOtherVideos', { detail: { category } }));
  };

  const handleCloseVideo = () => {
    setIsPlaying(false);
    setIsVideoPaused(false);
    if (ytPlayer) ytPlayer.pauseVideo();
    window.dispatchEvent(new CustomEvent('videoPlaybackStopped'));
  };

  const onPlayerReady = (event) => {
    setYtPlayer(event.target);
  };

  const onPlayerStateChange = (event) => {
    // 1 is PLAYING, 2 is PAUSED, 0 is ENDED
    if (event.data === 2 || event.data === 0) {
      setIsVideoPaused(true);
      if (event.data === 0) setIsPlaying(false);
      window.dispatchEvent(new CustomEvent('videoPlaybackStopped'));
    } else if (event.data === 1) {
      setIsVideoPaused(false);
      setIsPlaying(true);
      window.dispatchEvent(new CustomEvent('videoPlaybackStarted'));
      window.dispatchEvent(new CustomEvent('stopOtherVideos', { detail: { category } }));
    }
  };

  const ytOpts = {
    height: '100%',
    width: '100%',
    playerVars: {
      autoplay: 0,
      rel: 0,
      controls: 1,
      modestbranding: 1
    },
  };

  const scrollCarousel = (direction) => {
    if (carouselRef.current) {
      const scrollAmount = 350; 
      if (direction === 'up' || direction === 'down') {
        carouselRef.current.scrollBy({ top: direction === 'up' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
      } else {
        carouselRef.current.scrollBy({ left: direction === 'left' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
      }
    }
  };

  if (!videos || videos.length === 0) return null;

  const activeVideo = videos[activeIndex];

  return (
    <div className={`w-full flex flex-col justify-center font-main md:px-8 lg:px-12 pt-4 lg:pt-12 pb-4 lg:pb-6 max-w-[1600px] mx-auto ${isMobileLandscape ? 'h-[130vh] min-h-[500px]' : (!isMobile ? 'h-[100vh]' : 'h-auto')}`}>
      
      {/* Category Heading (Desktop) */}
      <div className={`${!isMobile ? 'flex' : 'hidden'} flex-col items-start w-full mb-6 px-2`}>
        <div className="flex items-center gap-4 mb-2">
          <div className={`w-16 h-16 lg:w-20 lg:h-20 rounded-full flex items-center justify-center flex-shrink-0 ${theme === 'red' ? 'bg-[#FEF2F2] text-brand-red' : 'bg-[#F0F5FF] text-[#1672EF]'}`}>
            {getCategoryIcon(category, theme)}
          </div>
          <h2 className={`text-4xl md:text-5xl lg:text-6xl font-hero font-extrabold tracking-widest uppercase ${theme === 'red' ? 'text-brand-red' : 'text-[#1672EF]'}`}>{category}</h2>
        </div>
        <p className="text-[#6A6A6A] font-medium text-sm md:text-base ml-2">{getCategorySubtitle(category)}</p>
      </div>

      {/* Category Heading (Mobile) */}
      <div className={`${isMobile ? 'flex' : 'hidden'} flex-col items-center justify-center w-full mb-4 px-2 text-center`}>
        <div className="flex flex-col items-center gap-2 mb-2">
          <div className={`w-12 h-12 rounded-full flex items-center justify-center ${theme === 'red' ? 'bg-[#FEF2F2] text-brand-red' : 'bg-[#F0F5FF] text-[#1672EF]'}`}>
            {getCategoryIcon(category, theme)}
          </div>
          <h2 className={`text-2xl sm:text-3xl font-hero font-extrabold tracking-widest uppercase text-center ${theme === 'red' ? 'text-brand-red' : 'text-[#1672EF]'}`}>{category}</h2>
        </div>
        <p className="text-[#6A6A6A] font-medium text-xs sm:text-sm text-center">{getCategorySubtitle(category)}</p>
      </div>

      <div className="w-full flex-1 min-h-0 px-0 bg-white md:rounded-[2rem] overflow-hidden relative shadow-[0_10px_40px_-15px_rgba(0,0,0,0.1)] border border-gray-100">
        
        {/* --- MOBILE VIEW --- */}
        <div className={`${isMobile ? 'block' : 'hidden'} w-full bg-white pb-8`}>
          {/* Main Video Section */}
          <div className="w-full aspect-video bg-black relative group">
            {isMobile && (
              <>
                <YouTube
                  videoId={activeVideo.id}
                  opts={ytOpts}
                  className="w-full h-full absolute inset-0"
                  iframeClassName="w-full h-full border-0 absolute inset-0"
                  onReady={onPlayerReady}
                  onStateChange={onPlayerStateChange}
                />
              </>
            )}
          </div>

          {/* Mobile Playlist Toggle */}
          <div className="overflow-hidden">
            <button 
              onClick={() => setIsMobilePlaylistOpen(!isMobilePlaylistOpen)}
              className="w-full py-4 border-b border-gray-200 flex justify-center items-center bg-white shadow-sm relative z-10 hover:bg-gray-50 transition-colors"
            >
                  <div className={`flex items-center gap-2 font-bold text-base uppercase ${theme === 'red' ? 'text-brand-red' : 'text-brand-blue'}`}>
                    <span>View more {category}</span>
                    <motion.div
                      animate={{ rotate: isMobilePlaylistOpen ? 180 : 0 }}
                      transition={{ duration: 0.3 }}
                    >
                      <FiChevronDown className="text-xl" />
                    </motion.div>
                  </div>
                </button>

                {/* Playlist Content */}
                <AnimatePresence>
                  {isMobilePlaylistOpen && (
                    <motion.div 
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="w-full flex flex-col bg-white overflow-hidden"
                    >
                      {videos.map((video, index) => {
                    const isActive = index === activeIndex;
                    return (
                      <div 
                        key={video.id + index}
                        onClick={() => {
                          setActiveIndex(index);
                        }}
                        className={`flex items-center gap-3 px-4 py-3 border-b border-gray-100 cursor-pointer transition-colors ${isActive ? 'bg-gray-50' : 'bg-white hover:bg-gray-50'}`}
                      >
                        {/* Thumbnail */}
                        <div className="relative w-28 sm:w-32 aspect-video flex-shrink-0 bg-gray-200 rounded overflow-hidden">
                          <ThumbnailImage video={video} isLarge={false} />
                          {!isActive && <div className="absolute inset-0 bg-white/30"></div>}
                        </div>
                        
                        {/* Info */}
                        <div className="flex-1 min-w-0">
                          <h4 className={`text-sm sm:text-base font-semibold truncate ${isActive ? (theme === 'red' ? 'text-red-900' : 'text-[#003366]') : 'text-gray-700'}`}>
                            {video.title}
                          </h4>
                        </div>
                        
                        <div className="text-xs text-gray-500 font-medium">
                          {isActive ? 'Playing' : ''}
                        </div>
                      </div>
                    );
                  })}
                    </motion.div>
                  )}
                </AnimatePresence>
          </div>
        </div>

        {/* --- DESKTOP VIEW --- */}
        <div className={`${!isMobile ? 'flex' : 'hidden'} relative w-full h-full bg-white lg:rounded-[2rem] flex-row p-4 lg:p-8 gap-6`}>
          
          {/* Main Video Section (Left) */}
          <div className="relative w-[65%] lg:w-[70%] h-full rounded-2xl overflow-hidden bg-black shadow-lg flex-shrink-0 group">
            {!isMobile && (
              <>
                <YouTube
                  videoId={activeVideo.id}
                  opts={ytOpts}
                  className="w-full h-full absolute inset-0"
                  iframeClassName="w-full h-full border-0 absolute inset-0"
                  onReady={onPlayerReady}
                  onStateChange={onPlayerStateChange}
                />
                {!isPlaying && !isMobileLandscape && (
                  <div 
                    className="absolute inset-0 z-10 cursor-pointer flex items-center justify-center bg-black"
                    onClick={handlePlayVideo}
                  >
                    <ThumbnailImage video={activeVideo} isLarge={true} />
                    <div className="absolute inset-0 bg-black/30 group-hover:bg-black/10 transition-colors"></div>
                    <div className="absolute w-16 h-16 md:w-20 md:h-20 bg-red-600 rounded-xl flex items-center justify-center shadow-[0_4px_20px_rgba(220,38,38,0.5)] transform group-hover:scale-110 transition-transform duration-300">
                      <FiPlay className="text-white text-3xl md:text-4xl ml-1" />
                    </div>
                  </div>
                )}
              </>
            )}
          </div>

          {/* Playlist Section (Right) */}
          <div className="flex-1 h-full flex flex-col bg-white overflow-hidden pr-2 rounded-2xl">
            {/* Header */}
            <div className="flex justify-between items-center mb-6 px-2 mt-2">
              <h2 className="text-xl font-bold text-gray-900 font-main">{category}</h2>
              <span className="text-sm font-semibold text-gray-500">{videos.length} Videos</span>
            </div>
            
            {/* List */}
            <div className="flex-1 overflow-y-auto overflow-x-hidden pr-2 flex flex-col gap-2" style={{ scrollbarWidth: 'thin', scrollbarColor: '#E5E7EB transparent' }}>
              {videos.map((video, index) => {
                const isActive = index === activeIndex;
                
                return (
                  <div 
                    key={video.id + index}
                    onClick={() => {
                      setActiveIndex(index);
                    }}
                    className={`flex items-center gap-4 p-3 rounded-2xl cursor-pointer transition-all duration-300 ${isActive ? (theme === 'red' ? 'bg-[#FEF2F2]' : 'bg-[#F0F5FF]') : 'bg-white hover:bg-gray-50'}`}
                  >
                    {/* Thumbnail */}
                    <div className="relative w-28 md:w-32 lg:w-36 aspect-video flex-shrink-0 bg-gray-200 rounded-xl overflow-hidden border border-gray-100 shadow-sm group-hover:shadow-md transition-all">
                      <ThumbnailImage video={video} isLarge={false} />
                      <div className="absolute inset-0 bg-white/10"></div>
                    </div>
                    
                    {/* Info */}
                    <div className="flex-1 min-w-0 flex justify-between items-center gap-2">
                      <div className="flex flex-col pr-2">
                        <h4 className={`text-sm md:text-base font-bold truncate ${isActive ? 'text-gray-900' : 'text-gray-800'}`}>
                          {video.title}
                        </h4>
                        <p className="text-xs text-gray-600 mt-1">{category}</p>
                      </div>
                      <div className={`text-xs md:text-sm font-bold whitespace-nowrap ${isActive ? (theme === 'red' ? 'text-brand-red' : 'text-[#1672EF]') : 'text-gray-500'}`}>
                        {isActive ? 'Playing' : ''}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VideoPlaylist;
