import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiPlay, FiX, FiChevronLeft, FiChevronRight } from 'react-icons/fi';

const ThumbnailImage = ({ video, isLarge }) => {
  const autoGeneratedThumbnail = `https://img.youtube.com/vi/${video.id}/hqdefault.jpg`;
  
  // It's a custom thumbnail if the user provided one that differs from the default script-generated one
  const isCustom = video.thumbnail && video.thumbnail !== autoGeneratedThumbnail;
  const fallbackImg = isCustom ? video.thumbnail : autoGeneratedThumbnail;
  
  const initialImg = isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg));
  
  const [imgSrc, setImgSrc] = useState(initialImg);

  React.useEffect(() => {
    setImgSrc(isCustom ? video.thumbnail : (video.customBg || (isLarge ? `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg` : fallbackImg)));
  }, [video.id, video.customBg, video.thumbnail, isLarge, isCustom, fallbackImg]);

  return (
    <img 
      src={imgSrc} 
      alt={video.title}
      className={isLarge ? "absolute inset-0 w-full h-full object-cover opacity-80" : "w-full h-full object-cover"}
      onError={() => {
        if (imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
      onLoad={(e) => {
        // Detect YouTube's 120px gray placeholder for maxresdefault
        if (e.target.naturalWidth <= 120 && imgSrc !== fallbackImg && !isCustom && !video.customBg) {
          setImgSrc(fallbackImg);
        }
      }}
    />
  );
};

const VideoPlaylist = ({ videos, category }) => {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const carouselRef = useRef(null);

  const scrollCarousel = (direction) => {
    if (carouselRef.current) {
      const scrollAmount = 350; 
      carouselRef.current.scrollBy({ left: direction === 'left' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
    }
  };

  if (!videos || videos.length === 0) return null;

  const activeVideo = videos[activeIndex];

  return (
    <div className="w-full bg-white h-screen py-4 md:py-8 flex justify-center items-center border-b border-gray-200 font-main">
      <div className="w-full h-full max-h-[1000px] max-w-[1600px] px-4 md:px-8">
        
        {/* Netflix-style Main Poster */}
        <div className="relative w-full h-full bg-black rounded-2xl md:rounded-[2rem] overflow-hidden shadow-[0_20px_50px_rgba(0,0,0,0.5)] group/poster">
          
          {/* Background Media */}
          <AnimatePresence>
            {!isPlaying && (
              <motion.div 
                key={activeVideo.id}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.8 }}
                className="absolute inset-0"
              >
                <ThumbnailImage video={activeVideo} isLarge={true} />
                {/* Netflix style Vignette & Gradients */}
                <div className="absolute inset-0 bg-gradient-to-t from-[#08080C] via-[#08080C]/40 to-transparent"></div>
                <div className="absolute inset-0 bg-gradient-to-r from-[#08080C]/80 via-transparent to-transparent"></div>
                <div className="absolute inset-0 shadow-[inset_0_0_100px_rgba(0,0,0,0.8)]"></div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Video Player */}
          {isPlaying && (
            <div className="absolute inset-0 z-50 bg-black">
              <button
                onClick={() => setIsPlaying(false)}
                className="absolute top-6 right-6 z-50 bg-white/20 backdrop-blur-md text-white p-3 rounded-full hover:bg-white hover:text-black transition-all shadow-xl"
              >
                <FiX className="text-2xl" />
              </button>
              <iframe
                src={`https://www.youtube.com/embed/${activeVideo.id}?autoplay=1&rel=0`}
                title={activeVideo.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full border-0"
              />
            </div>
          )}

          {/* Content Overlays */}
          {!isPlaying && (
            <div className="absolute inset-0 flex flex-col justify-between z-20 pointer-events-none pb-6 md:pb-12 pt-12 md:pt-20">
              
              {/* Top Section: Huge Category & Small Video Title */}
              <div className="w-full flex flex-col items-center px-4">
                <motion.h2 
                  key={`cat-${category}`}
                  initial={{ y: -20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  className="text-4xl md:text-6xl lg:text-7xl xl:text-8xl font-hero font-extrabold text-brand-blue tracking-widest uppercase drop-shadow-[0_4px_12px_rgba(0,0,0,0.8)] text-center leading-none"
                >
                  {category}
                </motion.h2>

                <motion.h1 
                  key={`title-${activeVideo.id}`}
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.1, duration: 0.6 }}
                  className="mt-4 md:mt-6 text-lg md:text-xl lg:text-2xl font-main font-semibold text-gray-200 text-center tracking-wide drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)] max-w-4xl"
                >
                  {activeVideo.title}
                </motion.h1>
              </div>

              {/* Center Section: Play Button */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none z-30">
                <motion.div 
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.3 }}
                  className="pointer-events-auto"
                >
                  <button
                    onClick={() => setIsPlaying(true)}
                    className="flex items-center gap-3 bg-white text-black px-10 py-4 md:py-5 rounded-full font-bold text-xl hover:bg-brand-blue hover:text-white hover:scale-105 transition-all shadow-[0_10px_30px_rgba(0,0,0,0.5)] group/playbtn"
                  >
                    <FiPlay className="text-2xl md:text-3xl fill-current" /> Watch Now
                  </button>
                </motion.div>
              </div>

              {/* Netflix-style Episode Carousel */}
              <div className="w-full pointer-events-auto relative mt-auto px-4 md:px-12 group/carousel">
                <style>{`
                  .hide-scrollbar::-webkit-scrollbar {
                    display: none;
                  }
                `}</style>
                
                <button 
                  onClick={() => scrollCarousel('left')}
                  className="absolute left-2 md:left-4 top-1/2 -translate-y-1/2 z-40 bg-black/80 hover:bg-white hover:text-black text-white p-2 md:p-3 rounded-full opacity-0 group-hover/carousel:opacity-100 transition-all duration-300 shadow-xl border border-white/20"
                >
                  <FiChevronLeft size={24} />
                </button>
                
                <button 
                  onClick={() => scrollCarousel('right')}
                  className="absolute right-2 md:right-4 top-1/2 -translate-y-1/2 z-40 bg-black/80 hover:bg-white hover:text-black text-white p-2 md:p-3 rounded-full opacity-0 group-hover/carousel:opacity-100 transition-all duration-300 shadow-xl border border-white/20"
                >
                  <FiChevronRight size={24} />
                </button>

                <div 
                  ref={carouselRef}
                  className="flex gap-3 md:gap-4 overflow-x-auto pb-4 pt-2 snap-x snap-mandatory hide-scrollbar relative" 
                  style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
                >
                  {videos.map((video, index) => {
                      const isActive = index === activeIndex;
                      const episodeNumber = String(index + 1).padStart(2, '0');
                      
                      return (
                        <button
                          key={video.id + index}
                          onClick={() => {
                            setActiveIndex(index);
                            setIsPlaying(false);
                          }}
                          className={`relative flex-shrink-0 w-40 md:w-56 lg:w-64 xl:w-72 aspect-video rounded-md overflow-hidden snap-start transition-all duration-500 cursor-pointer ${
                            isActive ? 'ring-2 ring-white scale-100 opacity-100 z-10' : 'scale-95 opacity-50 hover:scale-100 hover:opacity-100'
                          }`}
                        >
                          <ThumbnailImage video={video} isLarge={false} />
                          {/* Darken unselected */}
                          {!isActive && (
                            <div className="absolute inset-0 bg-black/40"></div>
                          )}
                          
                          {/* Number Overlay */}
                          <div className="absolute bottom-2 left-3">
                            <span className="text-white/90 font-bold text-lg md:text-xl font-hero drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
                              {episodeNumber}
                            </span>
                          </div>
                        </button>
                      );
                  })}
                </div>
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default VideoPlaylist;
